### ISSUE TITLE
already initialized constant DeepMerge::DEFAULT_FIELD_KNOCKOUT_PREFIX

### ISSUE THREAD

**Issue by firedev** [danielsdeleo/deep_merge#19]
Hi, here is what I am seeing every time my rails app starts:

```ruby
/[...]/gems/deep_merge-1.0.1/lib/deep_merge/core.rb:5: warning: already initialized constant DeepMerge::DEFAULT_FIELD_KNOCKOUT_PREFIX
/[...]/gems/rails_config-0.4.2/lib/rails_config/vendor/deep_merge.rb:4: warning: previous definition of DEFAULT_FIELD_KNOCKOUT_PREFIX was here
```

My `Gemfile`:
```ruby
gem 'deep_merge', require: 'deep_merge/rails_compat'
```

**Comment by firedev** [comment]
Fixed it https://github.com/railsconfig/rails_config/pull/110

**Comment by DannyBen** [comment]
When will this fix be available in the published gem?

**Comment by firedev** [comment]
You can use it right now: 
```ruby
gem 'rails_config', github: 'railsconfig/rails_config'
```

**Comment by DannyBen** [comment]
Thanks, I will try it like that, see if it stops complaining.
I see the last release of rails_config was a year ago, wondering why.

**Comment by firedev** [comment]
Sorry, no idea, just patched this thing because it kept annoying me.

**Comment by DannyBen** [comment]
Thanks, works for me as well.
