### ISSUE TITLE
Strange merge behaviour with keep_array_duplicates option

### ISSUE THREAD

**Issue by s-ga** [danielsdeleo/deep_merge#32]
Hi,

I'm facing a strange behavior with keep_array_duplicates option when destination hash is empty.
To illustrate I picked up the unit test case and changed `hash_dst` initial value to `{}`

```Ruby
hash_src = {"item" => ["2", "3"]}
hash_dst = {}
DeepMerge::deep_merge!(hash_src, hash_dst, {:keep_array_duplicates => true})
puts hash_dst
```

It produces:

```Ruby
{"item"=>["2", "3", "2", "3"]}
```

I was expecting something like :

```Ruby
{"item"=>["2", "3"]}
```

Am I wrong?

**Comment by Fryguy** [comment]
@nilo85 Can you comment here?

**Comment by science** [comment]
That is wacky (and sorry to come at this late). Notably if you use the native hash class extensions thing don't break so maybe as a workaround try to use the system that way. Seems like the method overwrite_unmergeables is behaving poorly with its calling function. But here's your problem working out of the box with the hash extension:
```
irb(main):018:0> hash_dst
=> {}
irb(main):019:0> hash_src = {"item" => ["2", "3"]}
=> {"item"=>["2", "3"]}
irb(main):020:0> hash_src.deep_merge(hash_dst)
=> {"item"=>["2", "3"]}
```

**Comment by ALTinners** [comment]
Made a pull that fixes this issue. @science You are merging the dest into the source in your case above ;)
