### ISSUE TITLE
{:merge_nil_values => true} does not work

### ISSUE THREAD

**Issue by markus7811** [danielsdeleo/deep_merge#35]
Source: 
`"DeletionPolicy": null` (JSON Style, in ruby its nil ;-)
Destination:
`"DeletionPolicy": "Snapshot"`

Destination.deep_merge!(Source, {:merge_nil_values => true})

Debug:
` ==>merging: :DeletionPolicy => nil :: "Snapshot"`

**Comment by Fryguy** [comment]
I'm not sure I understand the bug as it's working as defined.  `:merge_nil_values` states that when set to `true`, and when then source has a `nil`, it will overwrite the destination with that `nil`.  If `:merge_nil_values` is set to `false`, then `nil` values in the source are ignored (this is also the default).

```ruby
destination1 = {"DeletionPolicy" => "Snapshot"}
source1 = {"DeletionPolicy" => nil}
destination1.deep_merge!(source1, {:merge_nil_values => true})
# => {"DeletionPolicy"=>nil}
# This is expected as source1's nil is written into the destination

destination2 = {"DeletionPolicy" => "Snapshot"}
source2 = {"DeletionPolicy" => nil}
destination2.deep_merge!(source2, {:merge_nil_values => false})
# => {"DeletionPolicy"=>"Snapshot"}
# This is expected as source2's nil is ignored

destination3 = {"DeletionPolicy" => "Snapshot"}
source3 = {"DeletionPolicy" => nil}
destination3.deep_merge!(source3)
# => {"DeletionPolicy"=>"Snapshot"}
# This is expected as :merge_nil_values => false is the default
```

**Comment by markus7811** [comment]
Sorry, i found out, that the version installed via rubygems is not the version found here in git. Would it be possible to put this new version to rubygems?

**Comment by Fryguy** [comment]
Ah, I hadn't realize this wasn't released yet.  I'll look into it.
