### ISSUE TITLE
Simple nested usecase not working

### ISSUE THREAD

**Issue by ankilosaurus** [danielsdeleo/deep_merge#38]
`{a: {b: 1}}.deep_merge(a: {b: 2})` returns `{:a=>{:b=>1}}`

... using https://github.com/mcrossen/deepsort now which behaves as expected

**Comment by science** [comment]
This is a safety feature to not "overwrite unmergeables" by default. You should call the destructive form `deep_merge!` to get what you want:
```
{a: {b: 1}}.deep_merge(a: {b: 2})
{a: {b: 1}}.deep_merge!(a: {b: 2})
```
The idea is that if an interior object cannot actually merged (like an array) then it shouldn't be overwritten unless the ! operator is used.

**Comment by BaukJ** [comment]
I understand the reasoning, but some sort of warning might be nice so people don't assume it's working (I spent a while debugging this issue myself).
Personally I can't think of any use case where you want that to happen silently (happy to be corrected on this).

**Comment by Fryguy** [comment]
This is documented in the README, so I'm closing this one.
