### ISSUE TITLE
Is a new release being planned?

### ISSUE THREAD

**Issue by jay4git** [danielsdeleo/deep_merge#50]
Hello,
My org uses deep_merge for Puppet 6.x. 

The last release of deep_merge -- https://rubygems.org/gems/deep_merge/versions/1.2.1 -- was back in Nov 2017.

My org's security team prohibits the use of libraries which are not updated recently. 

Can it be possible to release a newer version of deep_merge, so that we are in compliance?

Thank you!

**Comment by science** [comment]
@jay4git - what would qualify as "updated" for your infosec team? Is there anything that doesn't work about this library or do you just need a date bump in the GEMFILE or something? I'd be reluctant to bump the version number without improving it in some way, but bumping some metadata seems fine as there has been minor activity even in 2020.. @danielsdeleo input would be welcome as the primary maintainer as always.

**Comment by jay4git** [comment]
Thanks @science and @Fryguy. What my org's security team looks for is that the release should be recent. So even though there is no CVE reported, if a release can be made available with any some fixes or newer Ruby files, that would be very helpful.

**Comment by science** [comment]
@Fryguy -- Yeah - bumping those versions make sense. It's weird in this sense @jay4git b/c Github is pretty good about flagging repos that depend on gems that have security vulnerabilities. And this repo doesn't have any of those flags right now. But many infosec people would prefer that all software is stored on a USB stick and put in a safe deposit box. Thanks @Fryguy for solving this!

**Comment by Fryguy** [comment]
Turns out Travis wasn't working, so I switched us over to GitHub Actions and added all the Rubies here: #52.  Everything seems working on all versions, which is nice.

**Comment by Fryguy** [comment]
Released 1.2.2 with support for Ruby up to Ruby 3.0 and also found a PR with a fix, so included that as well.
